version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./Server/Dockerfile
    ports: 
      - "3000:3000"
  client:
    build:
      context: .
      dockerfile: ./Client/Dockerfile
    ports:
      - "3001:3000"
    stdin_open: true